import * as React from "react";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Paper from "@mui/material/Paper";
import Button from "@mui/material/Button";
import { TextField } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";

export default function App() {
  const router = useRouter();
  const [username, setUsername] = React.useState("");

  const handleLogin = (e) => {
    e.preventDefault();
    if (username.trim()) {
      localStorage.setItem("username", username);
      router.push("/play");
    }
  };

  return (
    <>
      <Head>
        <title>Login - FITS Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          minHeight: "80vh",
          overflowY: "hidden",
        }}
      >
        <Paper
          sx={{
            width: "100%",
            maxWidth: 400,
            padding: 3,
            borderRadius: 2,
            boxShadow: 3,
            m: 2,
          }}
        >
          <Typography
            variant="h6"
            align="center"
            mb={2}
            sx={{
              fontWeight: "bold",
              backgroundImage: "linear-gradient(to right, #1e3a8a, #3b82f6)",
              backgroundClip: "text",
              color: "transparent",
            }}
          >
            Welcome to FITS Game
          </Typography>
          <form onSubmit={handleLogin}>
            <TextField
              fullWidth
              label="ชื่อเล่น"
              size="small"
              autoComplete="off"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              margin="normal"
              variant="outlined"
            />
            <Button
              fullWidth
              variant="contained"
              color="primary"
              type="submit"
              sx={{
                mt: 2,
                textTransform: "none",
                backgroundImage: "linear-gradient(to right, #1e3a8a, #3b82f6)",
              }}
            >
              เข้าสู่ระบบ
            </Button>
          </form>
        </Paper>
      </Box>
    </>
  );
}
