import * as React from "react";
import Head from "next/head";
import { io } from "socket.io-client";
import MemoryGame from "@/components/MemoryGame";
import QuestionGame from "@/components/QuestionGame";
import Layout from "@/components/Layout";
import withAuth from "@/components/withAuth";

function App() {
  const [socket, setSocket] = React.useState(null);
  const [username, setUsername] = React.useState("");
  const [users, setUsers] = React.useState([]);

  const [gameOnline, setGameOnline] = React.useState(0);

  React.useEffect(() => {
    const newSocket = io(process.env.NEXT_PUBLIC_SOCKET_SERVER);
    setSocket(newSocket);

    newSocket.on("updateUsers", (updatedUsers) => {
      setUsers(updatedUsers);
    });

    newSocket.on("gameActive", (gameNo) => {
      console.log("gameNo", gameNo);
      setGameOnline(gameNo);
    });

    return () => {
      newSocket.off("gameActive");

      newSocket.close();
    };
  }, []);

  React.useEffect(() => {
    if (socket) {
      const savedUsername = localStorage.getItem("username");
      if (savedUsername) {
        setUsername(savedUsername);
        socket.emit("login", savedUsername);
      }
    }
  }, [socket]);

  return (
    <React.Fragment>
      <Head>
        <title>Play - FITS Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={username} users={users}>
        {gameOnline === 0 && <QuestionGame username={username} />}
        {gameOnline === 1 && <MemoryGame username={username} />}
      </Layout>
    </React.Fragment>
  );
}

export default withAuth(App);
