import * as React from "react";
import Head from "next/head";
import Layout from "@/components/Layout/Layout";
import withAuth from "@/components/withAuth";
import {
  Typography,
  Grid,
  Stack,
  Box,
  Card,
  Divider,
  Chip,
  Button,
} from "@mui/material";
import ReplyRoundedIcon from "@mui/icons-material/ReplyRounded";
import { useRouter } from "next/router";
import AddIcon from "@mui/icons-material/Add";
import { TimelineCard } from "@/components/TimelineCard";
import ProjectDetailCard from "@/components/ProjectDetailCard/ProjectDetailCard";
import useDialog from "@/components/CustomDialog/useDialog";
import AddEventDialog from "@/components/CustomFormDialog/AddEventDialog";
function App() {
  const { showDialog, DialogComponent } = useDialog();
  const [username, setUsername] = React.useState("Jakakapn Pakeerat");
  const [users, setUsers] = React.useState([]);
  const [addEvOpen, setAddEvOpen] = React.useState(false);
  const router = useRouter();

  const sortedTimelineData = [...timelineData].sort(
    (a, b) => new Date(b.timestamp) - new Date(a.timestamp)
  );

  const initialProject = {
    buName: "Information Technology",
    projectName: "Implement Workflow System",
    jobType: "Development",
    reference: "REF001",
    priority: "High",
    status: "Pending",
  };

  const handleEdit = (data) => {
    console.log("Edit", data);
    // Return updated data after editing
    return { ...data, status: "Completed" }; // Example update
  };

  const handleDelete = (data) => {
    console.log("Delete", data);
    alert(`Deleted: ${data.projectName}`);
  };

  return (
    <React.Fragment>
      {DialogComponent}
      <AddEventDialog open={addEvOpen} onClose={() => setAddEvOpen(false)} />
      <Head>
        <title>Edit - Todoapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={username} users={users}>
        <Grid container spacing={1} sx={{ mt: -2 }}>
          <Grid item xs={12} md={3} sm={3}>
            <Grid container spacing={1} sx={{ mt: 1, mb: 1 }}>
              <Grid item xs={12} sm={12} md={12} sx={{ display: "flex" }}>
                <Stack
                  direction={"row"}
                  sx={{ cursor: "pointer" }}
                  onClick={() => router.push("/tasks")}
                >
                  <ReplyRoundedIcon sx={{ color: "#455A64" }} />
                  <Typography
                    sx={{
                      color: "#455A64",
                      fontWeight: "bold",
                      marginLeft: 0.5,
                    }}
                  >
                    Back
                  </Typography>
                </Stack>
              </Grid>
              <Grid item xs={12} sm={12} md={12} lg={12}>
                <Grid container spacing={1}>
                  <Grid item sm={12} md={12} xs={12}>
                    <ProjectDetailCard
                      initialData={initialProject}
                      onEdit={handleEdit}
                      onDelete={handleDelete}
                    />
                  </Grid>
                </Grid>
              </Grid>
            </Grid>
          </Grid>

          <Grid item xs={12} md={9} sm={9} sx={{ mt: 1, mb: 1 }}>
            <Grid container spacing={1}>
              <Grid
                item
                xs={12}
                sm={12}
                md={12}
                lg={12}
                sx={{ display: "flex", justifyContent: "space-between" }}
              >
                <Typography
                  sx={{
                    color: "#455A64",
                    fontWeight: "bold",
                    marginLeft: 0.5,
                    alignItems: "center",
                  }}
                >
                  Project Timeline
                </Typography>
                <Button
                  variant="contained"
                  size="small"
                  onClick={() => setAddEvOpen(true)}
                  sx={{
                    textTransform: "none",
                    backgroundImage:
                      "linear-gradient(to right, #1e3a8a, #3b82f6)",
                  }}
                  startIcon={<AddIcon />}
                >
                  Add Event
                </Button>
              </Grid>
              <Grid item xs={12} sm={12} md={12} lg={12}>
                <Card
                  sx={{
                    p: 2,
                    maxHeight: "700px",
                    overflowY: "auto",
                  }}
                >
                  <Stack spacing={2}>
                    <Box sx={{ width: "100%" }}>
                      {sortedTimelineData.map((item, index) => (
                        <TimelineCard key={item.id} item={item} index={index} />
                      ))}
                    </Box>
                  </Stack>
                </Card>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </Layout>
    </React.Fragment>
  );
}

export default withAuth(App);

const timelineData = [
  {
    id: "1",
    title: "Requirement Gathering",
    description: `Request by golf, 
    The requestor, would like to new operation for support unit RMA from the customer, provide requirement from them to us.`,
    timestamp: new Date("2024-12-01"),
    status: "Open",
  },
  {
    id: "2",
    title: "Design Phase",
    description: "Create wireframes and design mockups.",
    timestamp: new Date("2024-12-04"),
    status: "Pending",
  },
  {
    id: "3",
    title: "Design Phase",
    description: "Create wireframes and design mockups.",
    timestamp: new Date("2024-12-05"),
    status: "Completed",
  },
  {
    id: "4",
    title: "Design Phase",
    description: "Create wireframes and design mockups.",
    timestamp: new Date("2024-12-05"),
    status: "Cancel",
  },
  {
    id: "5",
    title: "Design Phase",
    description: "Create wireframes and design mockups.",
    timestamp: new Date("2024-12-05"),
    status: "Reopened",
  },
  {
    id: "6",
    title: "Design Phase",
    description: "Create wireframes and design mockups.",
    timestamp: new Date("2024-12-05"),
    status: "Hold",
  },

  // {
  //   id: "4",
  //   title: "Development",
  //   description: "Start implementing the project.",
  //   timestamp: new Date("2024-12-06"),
  //   status: "Completed",
  // },
  // {
  //   id: "4",
  //   title: "Development",
  //   description: "Start implementing the project.",
  //   timestamp: new Date("2024-12-06"),
  //   status: "Completed",
  // },
  // {
  //   id: "4",
  //   title: "Development",
  //   description: "Start implementing the project.",
  //   timestamp: new Date("2024-12-06"),
  //   status: "Completed",
  // },
];
